version: '3.3'
services:
  openresty:
    image: openresty/openresty:1.19.3.2
    ports:
      - "80:80"
      - "80:443"
      - "8001:8001"
      - "8072:8072"
      - "8074:8074"
      - "8004:8004"
    volumes:
      - /data/docker/openresty/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/docker/openresty/nginx-vhosts:/etc/nginx/conf.d
      - /data/docker/openresty/logs:/var/log/nginx
#      - ${SOURCE_SHARE_DIR}:/var/www
#      - ${NGINX_SSL_DIR}:/etc/letsencrypt
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
#        - TZ: "Asia/Shanghai"
    container_name: openresty
#    networks:
#        - backend
