version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m Dfile.encoding=UTF-8"
      - discovery.type=single-node
      - GID=1000 # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
      - UID=1000 # 可选 默认1000 主机当前用户 uid 解决挂载目录访问权限问题
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 1g
    volumes:
      - /data/docker/jenkins/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh:/root/.ssh

    ports:
      - 8080:8080
      - 50000:50000

volumes:
  esdata1:
    driver: local
