version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m Dfile.encoding=UTF-8"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 1g
    volumes:
      - /data/docker/jenkins/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh:/root/.ssh

    ports:
      - 8080:8080
      - 50000:50000

volumes:
  esdata1:
    driver: local
