version: "3.3"
services:
    redis:
        pid: "host"
        image: "redis:8.0.0-alpine"
        ports:
          - "6379:6379"
        container_name: redis
        shm_size: 64M
        cap_add:
          - SYS_RESOURCE
          - SYS_ADMIN
        stdin_open: true
        tty: true
        restart: "always"
        privileged: true
        volumes:
          - /data/docker/redis/data:/data:rw
#       entrypoint: /bin/sh
#        command: -c "sysctl -w net.core.somaxconn=511 && sysctl -w vm.overcommit_memory=1 && redis-server"
        environment:
          - GID=1000 # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
          - UID=1000 # 可选 默认1000 主机当前用户 uid 解决挂载目录访问权限问题
