version: '3'
services:
  wechat:
    image: bestwu/wechat:2.6.8.65deepin0
    container_name: wechat
    ipc: host
    network_mode: "host"
    cap_add:
      - SYS_ADMIN
#    devices:
#      - /dev/snd:/dev/snd:rwm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/downloads/wechatfiles:/WeChatFiles #使用自己用户目录
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    restart: "always"
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - GTK_IM_MODULE=fcitx
      - AUDIO_GID=63 # 可选 默认63（fedora） 主机audio gid 解决声音设备访问权限问题
      - GID=1000 # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
      - UID=1000 # 可选 默认1000 主机当前用户 uid 解决挂载目录访问权限问题
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
