#
# 需要把conf.d复制到/data/docker/openresty/conf目录下，里面的default.conf文件可以提供一个默认的80端口的服务
#
version: '3.3'
services:
  openresty:
    container_name: openresty1
    image: openresty/openresty:1.21.4.1-3-alpine-fat
    network_mode: "host"
    volumes:
      - /data/docker/openresty/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/docker/openresty/conf/conf.d:/etc/nginx/conf.d:ro
      - /data/docker/openresty/logs:/var/log/nginx:ro
      - /data/logs:/data/logs:rw
      - /home/jim/source/java/projects/goldendata-qd-client/dist:/data/goldendata-qd-client/dist:ro
      - /home/jim/source/java/projects/goldendata-qd-mp-client/dist:/data/goldendata-qd-mp-client/dist:ro
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    extra_hosts:
      - "gd.local:host-gateway"
      - "gd.mp.local:host-gateway"
      - "host.docker.internal:host-gateway"
